# 项目配置信息
app:
  env: dev
  debug: false
  juhe_key: "xxxxxxx"
  admin_email:
    -
  public_key: |
    -----BEGIN PUBLIC KEY-----
    xxxxxxx
    -----END PUBLIC KEY-----
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    xxxxx
    -----END RSA PRIVATE KEY-----

server:
  http: 9503
  websocket: 9504
  tcp: 9505

# 日志配置
log:
  # 日志文件路径 *请使用绝对路径*
  path: "/path/to/.../runtime"

# Redis 相关配置
redis:
  host: 127.0.0.1:6379
  auth: xxxxx
  database: 0

# Mysql 数据库配置
mysql:
  host: 127.0.0.1
  port: 3306
  charset: utf8mb4
  username: root
  password: xxxx
  database: go_chat
  collation: utf8mb4_general_ci

# Jwt 配置
jwt:
  secret: 836c3fea9bba4e04d51bd0fbcc5
  expires_time: 3600
  buffer_time: 3600

openai:
  key: "xxxx"
  proxy: "https://api.openai.com"

# 跨域配置
cors:
  origin: "*"
  headers: "Content-Type,Cache-Control,User-Agent,Keep-Alive,DNT,AccessToken,Authorization"
  methods: "OPTIONS,GET,POST,PUT,DELETE"
  credentials: false
  max_age: 600

# 文件系统配置【oss,qiniu 暂不支持】
filesystem:
  default: local
  local:
    # 文件保存的根目录
    root: "/path/xx/lumenim/"
    # 公开的 bucket
    bucket_public: "public"
    # 私有的 bucket
    bucket_private: "private"
    endpoint: "im-cdn.gzydong.com"
    ssl: false
  minio:
    secret_id: "xxxxxx"
    secret_key: "xxxxx"
    # 公开的 bucket
    bucket_public: "im-static"
    # 私有的 bucket
    bucket_private: "im-private"
    endpoint: "im-cdn.gzydong.com:9000"
    ssl: false

# 邮件配置
email:
  host: smtp.163.com
  port: 465
  username: xxxxx
  password: xxxxx
  fromname: "Lumen IM 在线聊天"